### ISSUE TITLE
Installing node.js via the InstallAndUpdate Batch file is broken

### ISSUE THREAD

**Issue by Conikku** [BlueberryWolf/ez-vencord-install#1]
https://mega.nz/folder/Y9kVhQYI#eKM_5v2IVc4cgZrrS-5IXA
[chocolatey.log](https://github.com/user-attachments/files/15903996/chocolatey.log)

**Comment by BlueberryWolf** [comment]
your pnpm is out of date, run this batch script to clear all previous versions of pnpm and install the version vencord uses
[fixpnpm.zip](https://github.com/user-attachments/files/15906798/fixpnpm.zip)

**Comment by BlueberryWolf** [comment]
@Conikku did this fix your issue?

**Comment by BlueberryWolf** [comment]
fixpnpm is now included in the main repo. I assume you're inactive on github. if you still have problems, open another issue
