### ISSUE TITLE
suddenly some plugins stopped working

### ISSUE THREAD

**Issue by mysterygothic** [BlueberryWolf/ez-vencord-install#10]
Hey, i really like your project. and i've been using it for weeks now.

sadly and out of no where plugins like ( Better microphone, Fake Deafen ) and other plugins stopped working while other plugins still work. i tried everything i re installed discord reinstalled node js , restarted the plugins. nothing works

**Comment by BlueberryWolf** [comment]
the plugins work but the UI broke again, and I can't be bothered to fix it rn. if you want to modify your settings you can find them at `%appdata%\Vencord\settings.json` under the BetterMicrophone and BetterScreenshare sections

**Comment by BlueberryWolf** [comment]
I'll fix it eventually. if another fork fixes it I'll merge their changes but I just can't be bothered to fix the UI again because I'd already configured my screenshare/mic settings and it saved, and still works fine

**Comment by mysterygothic** [comment]
can you tell me what should be the settings at least for the better microphone, in the settings.json i would really appreciate it. my settings normally be very high stereo without any advanced settings. now it just shows (  },
        "BetterMicrophone": {
            "enabled": true,
            "stores": {
                "MicrophoneStore": {}
            } )

**Comment by Denver3D** [comment]
> can you tell me what should be the settings at least for the better microphone, in the settings.json i would really appreciate it. my settings normally be very high stereo without any advanced settings. now it just shows ( }, "BetterMicrophone": { "enabled": true, "stores": { "MicrophoneStore": {} } )

here are the best settings for betterMic

"BetterMicrophone": {
            "enabled": true,
            "stores": {
                "MicrophoneStore": {
                    "currentProfile": {
                        "name": "High",
                        "channels": 2,
                        "channelsEnabled": true,
                        "voiceBitrate": 512,
                        "voiceBitrateEnabled": true
                    },
                    "profiles": [],
                    "simpleMode": true
                }
            }
        },
        
        
        also It seems because of the bug in the UI Another plugin doesn't work as it should and that is UserVoiceShow it does show me that my friends are in voice but when I wanna hover my mouse on it to see where they are it does disappear

**Comment by mysterygothic** [comment]
didn't work for me, unfortunately if only the old ui goes back/;
