### ISSUE TITLE
Better Screenshare Crashes the client

### ISSUE THREAD

**Issue by bruhonbruv** [BlueberryWolf/ez-vencord-install#4]
whenever clicking on the screenshare button in vc it crashes it over and over making it useless

**Comment by venomized** [comment]
+1

**Comment by BlueberryWolf** [comment]
Hi, sorry, I would fix this but my neighbours house burned down and the chemical residue destroyed my mouse and keyboard. I've replaced my keyboard but I cannot afford a new mouse at the moment. sounds crazy but I'm sorry. I will push a temporary fix to prevent the crash but don't expect it to work entirely

**Comment by BlueberryWolf** [comment]
this has been fixed now thanks to merging files from @Loukious\Vencord
