### ISSUE TITLE
BetterMicrophone doesnt work

### ISSUE THREAD

**Issue by bruhonbruv** [BlueberryWolf/ez-vencord-install#6]
It doesnt appear to work at all as of 8/15/2024 not sure if its the plugin or just me.

**Comment by BlueberryWolf** [comment]
> It doesnt appear to work at all as of 8/15/2024 not sure if its the plugin or just me.

works perfectly fine for my friends and I on the latest version of discord **stable** 
![image](https://github.com/user-attachments/assets/506dd51a-8a4b-4d69-abdc-a426f03902cc)

Make sure your ez-vencord-install is properly updated, and that an old installation is not conflicting.

Double check that noise suppression and echo cancellation are both ENTIRELY set to off in the settings (disabling it in the user panel is not enough)
![image](https://github.com/user-attachments/assets/3cc5ae94-a1ef-4e6b-8a93-73bb2d6a904a)

I am also using the "Experimental" audio subsystem.

If all else fails, try clearing "%appdata%\Vencord\dist", git clone the repo again (please do this, and not download as ZIP), then reinstall.

**Comment by BlueberryWolf** [comment]
> It doesnt appear to work at all as of 8/15/2024 not sure if its the plugin or just me.

try the fixes I suggested and if it still doesn't work open another issue with more info
